package demo.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import demo.model.Accounts;
import demo.model.AccountsExample;

@Mapper
@Repository
public interface AccountsRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accounts
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	long countByExample(AccountsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accounts
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	int deleteByExample(AccountsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accounts
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accounts
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	int insert(Accounts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accounts
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	int insertSelective(Accounts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accounts
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	List<Accounts> selectByExample(AccountsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accounts
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	Accounts selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accounts
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	int updateByExampleSelective(@Param("record") Accounts record, @Param("example") AccountsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accounts
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	int updateByExample(@Param("record") Accounts record, @Param("example") AccountsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accounts
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	int updateByPrimaryKeySelective(Accounts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accounts
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	int updateByPrimaryKey(Accounts record);
}