package demo.model;

import java.util.Date;

public class Accounts {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column accounts.id
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column accounts.mail_address
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	private String mailAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column accounts.password
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column accounts.updated_at
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column accounts.created_at
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	private Date createdAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column accounts.id
	 * @return  the value of accounts.id
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column accounts.id
	 * @param id  the value for accounts.id
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column accounts.mail_address
	 * @return  the value of accounts.mail_address
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	public String getMailAddress() {
		return mailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column accounts.mail_address
	 * @param mailAddress  the value for accounts.mail_address
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	public void setMailAddress(String mailAddress) {
		this.mailAddress = mailAddress == null ? null : mailAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column accounts.password
	 * @return  the value of accounts.password
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column accounts.password
	 * @param password  the value for accounts.password
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column accounts.updated_at
	 * @return  the value of accounts.updated_at
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column accounts.updated_at
	 * @param updatedAt  the value for accounts.updated_at
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column accounts.created_at
	 * @return  the value of accounts.created_at
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column accounts.created_at
	 * @param createdAt  the value for accounts.created_at
	 * @mbg.generated  Sat Jun 13 20:15:14 JST 2020
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}
}